# permissions for end users to view elasticcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticcache-viewer-role
rules:
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches/status
  verbs:
  - get
