# permissions for end users to edit elasticcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticcache-editor-role
rules:
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches/status
  verbs:
  - get
