
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches/finalizers
  verbs:
  - update
- apiGroups:
  - aws.sergeyshevch.dev
  resources:
  - elasticcaches/status
  verbs:
  - get
  - patch
  - update
